### ISSUE TITLE
Code blocks are not ignored

### ISSUE THREAD

**Issue by pitaj** [julianlam/nodebb-plugin-markdown#100]
See https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/lib/parse.ts#L81 for a regex that could help with this.

NodeBB/NodeBB#7132

**Comment by julianlam** [comment]
Yes, code blocks are not ignored, because that is valid markdown :stuck_out_tongue: 

You probably want mentions, no? In which case, I cannot reproduce.
