### ISSUE TITLE
How to disable use of markdown-it-checkbox...

### ISSUE THREAD

**Issue by alfazaz** [julianlam/nodebb-plugin-markdown#108]
Hello !

I'm trying to make a nodebb plugin to extend nodebb-plugin-markdown **without changing its code**... One problem is that I really don't want markdown-it-checkbox (problem with LaTeX formulas parsing, like $P[X]=...$)... I see no option to disable markdown-it-checkbox without removing it from this plugin (in updateParserRules). I would like not to have to change your code...

Is there a way to revert, **from another plugin**, the following code of your plugin (in index.js) ?

`
updateParserRules: function (parser) {
		// Add support for checkboxes
		parser.use(require('markdown-it-checkbox'), {
			divWrap: true,
			divClass: 'plugin-markdown',
		});
`

(Is there a way to disable the "parser.use" after this with a hook ?)

Thanks in advance !

**_More info on what I try to do here :_**
https://community.nodebb.org/topic/14141/proper-way-to-add-latex-with-markdown-it-texmath-and-katex-to-nodebb-plugin-markdown

**Comment by julianlam** [comment]
No need for something so complicated I think, I'll just make it a toggle-able option!

**Comment by julianlam** [comment]
v8.10.3 :)

**Comment by alfazaz** [comment]
Great, thanks ! I will be able to go forward on my plugin work tomorrow. :-)

**Comment by alfazaz** [comment]
@julianlam Just a detail : you forgot to remove a console.log in index.js (line 238)... ;-)

You can close this issue after.

**Comment by julianlam** [comment]
v8.10.4 :laughing:
