### ISSUE TITLE
Parse problem with bold+italic

### ISSUE THREAD

**Issue by alfazaz** [julianlam/nodebb-plugin-markdown#112]
Hello !

I found a strange problem with bold+italic parsing. For example, when I type (on my nodebb v1.13.0 forum or on nodebb community forum) :

```
l'*(essai)*...  -> it works [ (essai) is in italics ].
l'**(essai)**... -> it works [ (essai) is in bold ].
l'***(essai)***... -> it doesn't works... It works only if I add spaces around the *** chars.

```
There must be something wrong in the parsing for bold+italic. ;-)

**Comment by julianlam** [comment]
@alfazaz It certainly seems like it -- I am unable to reproduce on [the official markdown-it demo](https://markdown-it.github.io/), so it certainly points to NodeBB as the culprit :smile: 

Perhaps we should update the markdown-it version...

**Comment by alfazaz** [comment]
Ok... I will wait for the improvement.

**Comment by julianlam** [comment]
v8.11.0

**Comment by julianlam** [comment]
9073081
