### ISSUE TITLE
Ability to set a default highlight language instead of autodetection

### ISSUE THREAD

**Issue by T3P3** [julianlam/nodebb-plugin-markdown#168]
Most users on out forum do not know to set the code syntax highlighting to a specific language (which make sense as its not a supported language anyway, however JSON works quite nicely as a substitute formatting).

It would be great if there was an option to override the highlight.js autodetect and insert a hardcoded language into every code block. The hard coded language format could be set in the markdown plugin settings, the user could over ride it if they wished (by replacing the ``` ` ` `JSON``` or whatever with what they wanted

**Comment by julianlam** [comment]
Hi there @T3P3 

Thanks for the suggestion, it is a good one, and I will look into implementing it.

A complication exists in that highlight.js it may not be actually used directly, but might be called as a markdown plugin, which might make it a dependency of a dependency of a dependency... 😬 

We shall see.

**Comment by pitaj** [comment]
I'm confused. It seems like you already can set the language manually with

   ```lang

https://community.nodebb.org/post/85843

**Comment by T3P3** [comment]
Yes that's is exactly it - allow the forum admins to set a default language for code blocks in order to override highlight.js autodetection because autodetection is undesirable if the language in the code block is not a supported one.

@julianlam to get around the dependencies issues, potentially have the text inserted after the backticks:
` ``` <admin set default> `

with the default being blank?

**Comment by julianlam** [comment]
Potentially, yes... the difficult part is that while the markdown parser we use has the appropriate hooks and such for mutation of inputs, I cannot easily say whether this is doable quickly or not :smile: 

Their plugin API is... difficult, to put it lightly.
