### ISSUE TITLE
sometimes code blocks are not styled

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-markdown#31]
cold load a few times with cache disabled
https://community.nodebb.org/topic/3860/invalid-file-error-when-trying-to-upload-an-avatar-affects-all-users-and-all-image-file-types 

![image](https://cloud.githubusercontent.com/assets/2583394/6198803/6649ccc0-b3e7-11e4-8833-7078fba48a8f.png)

**Comment by julianlam** [comment]
#32 closes this

**Comment by julianlam** [comment]
v0.8.6
