### ISSUE TITLE
Your version of NodeBB (v0.7.0) is only cleared to upgrade to v3.0.4

### ISSUE THREAD

**Issue by tfraley** [julianlam/nodebb-plugin-markdown#44]
New to nodebb. 

Any reason I am getting this error when clicking the upgrade button in NodeBB v7.0

"Your version of NodeBB (v0.7.0) is only cleared to upgrade to v3.0.4 of this plugin. Please update your NodeBB if you wish to install a newer version of this plugin."

**Comment by julianlam** [comment]
Yup! The latest version of Markdown published today (v4.0.0) includes functionality that only NodeBB v0.7.1 contains.

As NodeBB v0.7.1 has not been released yet, you are advised to stick with v3.0.4 until then :smile:

**Comment by julianlam** [comment]
Don't worry, the two versions are quite similar, functionality-wise :smile:

**Comment by tfraley** [comment]
Aaa ok there is a 7.1 just not out yet. found it funny a plugin is asking for something that is not out yet.
