### ISSUE TITLE
$ characters are suppressed if used more than once

### ISSUE THREAD

**Issue by ip6li** [julianlam/nodebb-plugin-markdown#45]
If following fragment entered with markdown

    sound_prefix : $${sounds_dir}/de/tts/google

NodeBB displays
sound_prefix : ${sounds_dir}/de/tts/google
only. One '$' is missing. Expected behaviour: Both '$' should be displayed. Preview shows '$$' but page shows '$' only.

**Comment by julianlam** [comment]
Wow, weird bug, thanks @ip6li...!

**Comment by julianlam** [comment]
Reported upstream:

psychobunny/templates.js#43
