### ISSUE TITLE
how can I upload image in the editor

### ISSUE THREAD

**Issue by FoghostCn** [julianlam/nodebb-plugin-markdown#49]
how can I upload image in the editor,with markdown I can insert image with `![text](url)`, but how can i upload it

**Comment by julianlam** [comment]
Hi there,

You can enable the option to upload images in the ACP settings:

![selection_051](https://cloud.githubusercontent.com/assets/923011/9441841/5cc522ee-4a46-11e5-8144-c6f6c0b85501.png)
