### ISSUE TITLE
nodebb-plugin-markdown is and nodebb-plugin-iframely break each other in nodebb v0.9.x?

### ISSUE THREAD

**Issue by metahusk** [julianlam/nodebb-plugin-markdown#56]
When I have both nodebb-plugin-markdown and nodebb-plugin-iframely activated nodebb no longer works. When I deactivate either it fixes this issue. The administration menu still works to disable the plugins but I did not try refresh.

Thanks for your hard work!

iframely 0.6.1
markdown 4.0.7

**Comment by julianlam** [comment]
I can't seem to reproduce, both plugins are running here. Do you have an API key defined in iframely?
