### ISSUE TITLE
[outdated] nodebb-plugin-markdown installed v4.0.10, package.json requires 4.0.9

### ISSUE THREAD

**Issue by Pappmann** [julianlam/nodebb-plugin-markdown#61]
im running latest git version of nodebb

**Comment by julianlam** [comment]
Normal, looks like you'll need to upgrade your core NodeBB :smile:

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/c18d185ce48dad38a400f1d3c2e5e5e8769a6ca0
