### ISSUE TITLE
composer help link to CommonMark should open in a new tab

### ISSUE THREAD

**Issue by BenLubar** [julianlam/nodebb-plugin-markdown#72]
The composer help dialog is effectively a separate window to the composer. If a user clicks the link to CommonMark, it closes the composer and changes the forum tab to a different website. This confuses at least one of my users. :rat:

**Comment by julianlam** [comment]
Hm... is `externalBlank` enabled? That should cause the composer help link to also be `target="_blank"`. It's a Markdown option, by the way.

**Comment by BenLubar** [comment]
hmm, that would make all posted links be target="_blank", wouldn't it?

**Comment by julianlam** [comment]
Yes... the idea is to not mess around with link opening behaviour, so if you click a link, it nagivates in that tab, otherwise you shift-click/ctrl-click to open in new window/tab respectively.
