### ISSUE TITLE
Tables not responsive

### ISSUE THREAD

**Issue by huegelc** [julianlam/nodebb-plugin-markdown#73]
On mobile devices tables on posts are not responsive. I would like to add a div element to the template:
```
<div style="overflow-x:auto;">
  <table>
    ...
  </table>
</div>
```

 that generates the html code but don´t know where to look. Would be nice if you can point me to the right direction. Thank you

**Comment by julianlam** [comment]
Your best bet would be to modify the theme stylesheet itself (github.com/NodeBB/nodebb-theme-persona) and add the overflow declaration there.

The plugin itself doesn't actually construct the HTML, that's done by the dependent markdown-it plugin.
