### ISSUE TITLE
Allow usage of markdown-it plugins

### ISSUE THREAD

**Issue by benjaminabel** [julianlam/nodebb-plugin-markdown#75]
It would be nice to allow admin to add [markdown-it plugins](https://www.npmjs.com/browse/keyword/markdown-it-plugin) in the acp.
However this would needs:
1. to install the plugins from npm
2. add the require to the `js` file for all plugins added.

```
var md = require('markdown-it')()
            .use(require('markdown-it-deflist'));
```

Do you think it's possible?

**Comment by julianlam** [comment]
Hi @benjaminabel :smile: 

Yes it is definitely possible, and it's something I've wanted to add to the plugin, so will have to look into this soon.

**Comment by benjaminabel** [comment]
Thanks for your quick answer @julianlam I was just looking into the
markdown-it code to understand clearly how the use function works and it
seems easy to implement.
I can try to do this however I'd like to know if you have any requirements
on the acp implementation.

**Comment by julianlam** [comment]
Yes, in general I want to make it trivial to install the plugins, but I want the list of plugins to be hardcoded into the file itself (and others can add it via pull request if required).

So in the plugin itself, there would be an array like `['markdown-it-deflist']`, and the ACP frontend would show this as a list of plugins to activate and/or install.

Likewise, on NodeBB start, if the markdown plugin detects these packages available, it will automatically utilise them.

Disabling is just a matter of uninstalling the relevant npm package.

**Comment by benjaminabel** [comment]
If I correctly understand the plugin section would look very similar to the
main plugin acp however some plugins may pass some specific configuration,
how can we handle this.

Yes, in general I want to make it trivial to install the plugins, but I
want the list of plugins to be hardcoded into the file itself (and others
can add it via pull request if required).

So in the plugin itself, there would be an array like
['markdown-it-deflist'], and the ACP frontend would show this as a list of
plugins to activate and/or install.

Likewise, on NodeBB start, if the markdown plugin detects these packages
available, it will automatically utilise them.

Disabling is just a matter of uninstalling the relevant npm package.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/julianlam/nodebb-plugin-markdown/issues/75#issuecomment-225613770>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA9S-jfPq01VNsxcojkIN10CkJMOvbUzks5qLXVEgaJpZM4Izn2i>
.

**Comment by julianlam** [comment]
That's more difficult... are these a minority, or do all plugins require some level of configuration?

If they only require basic configuration or work with sensible defaults, we could store those defaults alongside in the markdown plugin itself...

Lends credence to the idea that the markdown plugin would only accept a small subset of plugins.

**Comment by benjaminabel** [comment]
@julianlam I'm closing since it's too old.
