### ISSUE TITLE
Update highlight.js

### ISSUE THREAD

**Issue by KitsuneSolar** [julianlam/nodebb-plugin-markdown#77]
Hi! How update highlight.js to latest version?
I replace /public/js/highlight.js to v9.4, it working. But browser console give me error:

```
nodebb.min.js > Uncaught Error: Mismatched anonymous define() module: function (){return t.hljs}
http://requirejs.org/docs/errors.html#mismatch
```

HighlightJS v9.4 support require.js, but i not know how connect this version to NodeBB.

**Comment by julianlam** [comment]
Thanks, will take a look today

**Comment by julianlam** [comment]
I added highlight.js years ago, so there's probably a better way to include the lib now.

**Comment by KitsuneSolar** [comment]
@julianlam I think this will cause an error request.js. I will try code and report.

**Comment by julianlam** [comment]
:+1:
