### ISSUE TITLE
Extra spaces upon formatting incorrectly offsets selection.

### ISSUE THREAD

**Issue by yariplus** [julianlam/nodebb-plugin-markdown#85]
If you select an extra space and hit a formatting button, the new selection is offset.

**Comment by yariplus** [comment]
This is especially annoying because some browsers automatically select a leading space when double-clicking.

**Comment by pitaj** [comment]
Can you provide a couple examples of what you mean? I.e. what you expect to happen vs what actually happens.

**Comment by yariplus** [comment]
Sure thing. When I select a word here:

https://puu.sh/wF9UW/e712b59eb8.png

I would expect the word link to be part of the link text (which it is) and for the link url to be selected. Instead this happens:

https://puu.sh/wF9VF/602f6734b7.png

**Comment by julianlam** [comment]
It looks like the **simpler** logic would've been sufficient... that is, if you highlight `link `, then `link ` makes it into the anchor, space and all.

There's some logic here to handle leading and trailing whitespace, but it doesn't adjust the selection values as well.

**Comment by julianlam** [comment]
Logic was [added in this commit](https://github.com/NodeBB/nodebb-plugin-composer-default/commit/d9f195fe29d1b62f27e1a8336ec9a2cd2c660534) by @BenLubar 👍

**Comment by julianlam** [comment]
0621708 and nodebb/nodebb-plugin-composer-default@d889cad16377081d43bafffba1096cf20064a38a

**Comment by julianlam** [comment]
65329b9bd75d2566a328170b6edaa1eb86109e1f
