### ISSUE TITLE
Support markdown checkboxes

### ISSUE THREAD

**Issue by pitaj** [julianlam/nodebb-plugin-markdown#86]
ref NodeBB/NodeBB#6235

This could be useful:
https://www.npmjs.com/package/markdown-it-checkbox

**Comment by julianlam** [comment]
Yep, using a markdown-it plugin is the easiest way to get this done, since any other method is essentially rewriting the same plugin anyway.

**Comment by antoine-pous** [comment]
Any news about this feature? I've seen a PR wich can be updated and merged to implement markdwon-it :)

**Comment by julianlam** [comment]
Not yet, but thank you for the reminder 🙂

**Comment by julianlam** [comment]
I do have it working, by the way... but I'd like to finish it up so that if you click on the checkbox it updates the post. Still working on that part.
