### ISSUE TITLE
Detection of highlight.js styles directory does not work sometimes

### ISSUE THREAD

**Issue by gramakri** [julianlam/nodebb-plugin-markdown#99]
The code at https://github.com/julianlam/nodebb-plugin-markdown/blob/master/index.js#L121 assumes that highlight.js is installed one level below. Depending on the plugins installed and the order of installation, the module moves around and is sometimes actually located at `__dirname/node_modules/hghlight.js`.

To fix, maybe we can change the path detection to `path.resolve(require.resolve('highlight.js'), '../../styles')`. This gets the path of the resolved index.js in highligh.js and gets the styles directory relative to that.

**Comment by julianlam** [comment]
:clap: TIL about `require.resolve()`

**Comment by julianlam** [comment]
v8.8.7

**Comment by julianlam** [comment]
I ended up using `path.join` anyway, since we're appending a relative path to the resolved value. I actually have no idea if `path.resolve` has more overhead, to be honest.
